export const PAWAPAY_COUNTRIES: Record<
  string,
  {
    name: string;
    flag: string;
    currency: string;
    dialCode: string;
    phonePlaceholder: string;
    operators: { code: string; name: string; logo: string }[];
  }
> = {
  COG: {
    name: "Congo (Brazzaville)",
    flag: "🇨🇬",
    currency: "XAF",
    dialCode: "+242",
    phonePlaceholder: "+242 06 000 0000",
    operators: [
      { code: "AIRTEL_COG", name: "Airtel Money", logo: "🔴" },
      { code: "MTN_COG", name: "MTN Mobile Money", logo: "🟡" },
    ],
  },
  CMR: {
    name: "Cameroun",
    flag: "🇨🇲",
    currency: "XAF",
    dialCode: "+237",
    phonePlaceholder: "+237 6XX XXX XXX",
    operators: [
      { code: "MTN_CMR", name: "MTN Mobile Money", logo: "🟡" },
      { code: "ORANGE_CMR", name: "Orange Money", logo: "🟠" },
    ],
  },
  CIV: {
    name: "Côte d'Ivoire",
    flag: "🇨🇮",
    currency: "XOF",
    dialCode: "+225",
    phonePlaceholder: "+225 07 XX XX XX XX",
    operators: [
      { code: "ORANGE_CIV", name: "Orange Money", logo: "🟠" },
      { code: "MTN_CIV", name: "MTN Mobile Money", logo: "🟡" },
      { code: "MOOV_CIV", name: "Moov Money", logo: "🔵" },
      { code: "WAVE_CIV", name: "Wave", logo: "🌊" },
    ],
  },
  SEN: {
    name: "Sénégal",
    flag: "🇸🇳",
    currency: "XOF",
    dialCode: "+221",
    phonePlaceholder: "+221 7X XXX XX XX",
    operators: [
      { code: "ORANGE_SEN", name: "Orange Money", logo: "🟠" },
      { code: "FREE_SEN", name: "Free Money", logo: "🔵" },
      { code: "WAVE_SEN", name: "Wave", logo: "🌊" },
    ],
  },
  GHA: {
    name: "Ghana",
    flag: "🇬🇭",
    currency: "GHS",
    dialCode: "+233",
    phonePlaceholder: "+233 24 XXX XXXX",
    operators: [
      { code: "MTN_GHA", name: "MTN Mobile Money", logo: "🟡" },
      { code: "VODAFONE_GHA", name: "Vodafone Cash", logo: "🔴" },
      { code: "AIRTELTIGO_GHA", name: "AirtelTigo Money", logo: "🔴" },
    ],
  },
  NGA: {
    name: "Nigeria",
    flag: "🇳🇬",
    currency: "NGN",
    dialCode: "+234",
    phonePlaceholder: "+234 80X XXX XXXX",
    operators: [
      { code: "MTN_NGA", name: "MTN MoMo", logo: "🟡" },
      { code: "AIRTEL_NGA", name: "Airtel Money", logo: "🔴" },
    ],
  },
  KEN: {
    name: "Kenya",
    flag: "🇰🇪",
    currency: "KES",
    dialCode: "+254",
    phonePlaceholder: "+254 7XX XXX XXX",
    operators: [
      { code: "MPESA_KEN", name: "M-Pesa", logo: "🟢" },
      { code: "AIRTEL_KEN", name: "Airtel Money", logo: "🔴" },
    ],
  },
  TZA: {
    name: "Tanzanie",
    flag: "🇹🇿",
    currency: "TZS",
    dialCode: "+255",
    phonePlaceholder: "+255 7XX XXX XXX",
    operators: [
      { code: "MPESA_TZA", name: "M-Pesa", logo: "🟢" },
      { code: "TIGO_TZA", name: "Tigo Pesa", logo: "🔵" },
      { code: "AIRTEL_TZA", name: "Airtel Money", logo: "🔴" },
      { code: "HALOTEL_TZA", name: "Halopesa", logo: "🟣" },
    ],
  },
  UGA: {
    name: "Ouganda",
    flag: "🇺🇬",
    currency: "UGX",
    dialCode: "+256",
    phonePlaceholder: "+256 7XX XXX XXX",
    operators: [
      { code: "MTN_UGA", name: "MTN Mobile Money", logo: "🟡" },
      { code: "AIRTEL_UGA", name: "Airtel Money", logo: "🔴" },
    ],
  },
  ZMB: {
    name: "Zambie",
    flag: "🇿🇲",
    currency: "ZMW",
    dialCode: "+260",
    phonePlaceholder: "+260 9X XXX XXXX",
    operators: [
      { code: "MTN_ZMB", name: "MTN Mobile Money", logo: "🟡" },
      { code: "AIRTEL_ZMB", name: "Airtel Money", logo: "🔴" },
      { code: "ZAMTEL_ZMB", name: "Zamtel Kwacha", logo: "🟢" },
    ],
  },
  ZWE: {
    name: "Zimbabwe",
    flag: "🇿🇼",
    currency: "USD",
    dialCode: "+263",
    phonePlaceholder: "+263 7X XXX XXXX",
    operators: [
      { code: "ECOCASH_ZWE", name: "EcoCash", logo: "🟢" },
      { code: "ONEMONEY_ZWE", name: "OneMoney", logo: "🔴" },
    ],
  },
  MOZ: {
    name: "Mozambique",
    flag: "🇲🇿",
    currency: "MZN",
    dialCode: "+258",
    phonePlaceholder: "+258 8X XXX XXXX",
    operators: [
      { code: "MPESA_MOZ", name: "M-Pesa", logo: "🟢" },
      { code: "EMOLA_MOZ", name: "eMola", logo: "🔵" },
    ],
  },
  GIN: {
    name: "Guinée",
    flag: "🇬🇳",
    currency: "GNF",
    dialCode: "+224",
    phonePlaceholder: "+224 6XX XXX XXX",
    operators: [
      { code: "MTN_GIN", name: "MTN Mobile Money", logo: "🟡" },
      { code: "ORANGE_GIN", name: "Orange Money", logo: "🟠" },
    ],
  },
  BFA: {
    name: "Burkina Faso",
    flag: "🇧🇫",
    currency: "XOF",
    dialCode: "+226",
    phonePlaceholder: "+226 6X XX XX XX",
    operators: [
      { code: "ORANGE_BFA", name: "Orange Money", logo: "🟠" },
      { code: "MOOV_BFA", name: "Moov Money", logo: "🔵" },
    ],
  },
  MLI: {
    name: "Mali",
    flag: "🇲🇱",
    currency: "XOF",
    dialCode: "+223",
    phonePlaceholder: "+223 7X XX XX XX",
    operators: [
      { code: "ORANGE_MLI", name: "Orange Money", logo: "🟠" },
      { code: "MOOV_MLI", name: "Moov Money", logo: "🔵" },
    ],
  },
  MDG: {
    name: "Madagascar",
    flag: "🇲🇬",
    currency: "MGA",
    dialCode: "+261",
    phonePlaceholder: "+261 3X XX XXX XX",
    operators: [
      { code: "MVOLA_MDG", name: "MVola", logo: "🔴" },
      { code: "AIRTEL_MDG", name: "Airtel Money", logo: "🔴" },
      { code: "ORANGE_MDG", name: "Orange Money", logo: "🟠" },
    ],
  },
  RWA: {
    name: "Rwanda",
    flag: "🇷🇼",
    currency: "RWF",
    dialCode: "+250",
    phonePlaceholder: "+250 7XX XXX XXX",
    operators: [
      { code: "MTN_RWA", name: "MTN Mobile Money", logo: "🟡" },
      { code: "AIRTEL_RWA", name: "Airtel Money", logo: "🔴" },
    ],
  },
  BEN: {
    name: "Bénin",
    flag: "🇧🇯",
    currency: "XOF",
    dialCode: "+229",
    phonePlaceholder: "+229 9X XX XX XX",
    operators: [
      { code: "MTN_BEN", name: "MTN Mobile Money", logo: "🟡" },
      { code: "MOOV_BEN", name: "Moov Money", logo: "🔵" },
    ],
  },
  TGO: {
    name: "Togo",
    flag: "🇹🇬",
    currency: "XOF",
    dialCode: "+228",
    phonePlaceholder: "+228 9X XX XX XX",
    operators: [
      { code: "TMONEY_TGO", name: "T-Money", logo: "🟡" },
      { code: "MOOV_TGO", name: "Moov Money", logo: "🔵" },
    ],
  },
  GAB: {
    name: "Gabon",
    flag: "🇬🇦",
    currency: "XAF",
    dialCode: "+241",
    phonePlaceholder: "+241 0X XX XX XX",
    operators: [{ code: "AIRTEL_GAB", name: "Airtel Money", logo: "🔴" }],
  },
  SLE: {
    name: "Sierra Leone",
    flag: "🇸🇱",
    currency: "SLL",
    dialCode: "+232",
    phonePlaceholder: "+232 7X XXX XXX",
    operators: [
      { code: "ORANGE_SLE", name: "Orange Money", logo: "🟠" },
      { code: "AFRIMONEY_SLE", name: "Afrimoney", logo: "🟢" },
    ],
  },
  GNB: {
    name: "Guinée-Bissau",
    flag: "🇬🇼",
    currency: "XOF",
    dialCode: "+245",
    phonePlaceholder: "+245 9X XXX XXXX",
    operators: [{ code: "MTN_GNB", name: "MTN Mobile Money", logo: "🟡" }],
  },
  COD: {
    name: "RD Congo",
    flag: "🇨🇩",
    currency: "CDF",
    dialCode: "+243",
    phonePlaceholder: "+243 8X XXX XXXX",
    operators: [
      { code: "AIRTEL_COD", name: "Airtel Money", logo: "🔴" },
      { code: "MPESA_COD", name: "M-Pesa", logo: "🟢" },
      { code: "ORANGE_COD", name: "Orange Money", logo: "🟠" },
    ],
  },
  ETH: {
    name: "Éthiopie",
    flag: "🇪🇹",
    currency: "ETB",
    dialCode: "+251",
    phonePlaceholder: "+251 9X XXX XXXX",
    operators: [{ code: "TELEBIRR_ETH", name: "Telebirr", logo: "🔵" }],
  },
};

export const WORLD_COUNTRIES: { code: string; name: string; flag: string }[] = [
  { code: "AF", name: "Afghanistan", flag: "🇦🇫" },
  { code: "AL", name: "Albanie", flag: "🇦🇱" },
  { code: "DZ", name: "Algérie", flag: "🇩🇿" },
  { code: "AD", name: "Andorre", flag: "🇦🇩" },
  { code: "AO", name: "Angola", flag: "🇦🇴" },
  { code: "AG", name: "Antigua-et-Barbuda", flag: "🇦🇬" },
  { code: "AR", name: "Argentine", flag: "🇦🇷" },
  { code: "AM", name: "Arménie", flag: "🇦🇲" },
  { code: "AU", name: "Australie", flag: "🇦🇺" },
  { code: "AT", name: "Autriche", flag: "🇦🇹" },
  { code: "AZ", name: "Azerbaïdjan", flag: "🇦🇿" },
  { code: "BS", name: "Bahamas", flag: "🇧🇸" },
  { code: "BH", name: "Bahreïn", flag: "🇧🇭" },
  { code: "BD", name: "Bangladesh", flag: "🇧🇩" },
  { code: "BB", name: "Barbade", flag: "🇧🇧" },
  { code: "BY", name: "Biélorussie", flag: "🇧🇾" },
  { code: "BE", name: "Belgique", flag: "🇧🇪" },
  { code: "BZ", name: "Belize", flag: "🇧🇿" },
  { code: "BJ", name: "Bénin", flag: "🇧🇯" },
  { code: "BT", name: "Bhoutan", flag: "🇧🇹" },
  { code: "BO", name: "Bolivie", flag: "🇧🇴" },
  { code: "BA", name: "Bosnie-Herzégovine", flag: "🇧🇦" },
  { code: "BW", name: "Botswana", flag: "🇧🇼" },
  { code: "BR", name: "Brésil", flag: "🇧🇷" },
  { code: "BN", name: "Brunéi", flag: "🇧🇳" },
  { code: "BG", name: "Bulgarie", flag: "🇧🇬" },
  { code: "BF", name: "Burkina Faso", flag: "🇧🇫" },
  { code: "BI", name: "Burundi", flag: "🇧🇮" },
  { code: "CV", name: "Cap-Vert", flag: "🇨🇻" },
  { code: "KH", name: "Cambodge", flag: "🇰🇭" },
  { code: "CM", name: "Cameroun", flag: "🇨🇲" },
  { code: "CA", name: "Canada", flag: "🇨🇦" },
  { code: "CF", name: "Centrafrique", flag: "🇨🇫" },
  { code: "TD", name: "Tchad", flag: "🇹🇩" },
  { code: "CL", name: "Chili", flag: "🇨🇱" },
  { code: "CN", name: "Chine", flag: "🇨🇳" },
  { code: "CO", name: "Colombie", flag: "🇨🇴" },
  { code: "KM", name: "Comores", flag: "🇰🇲" },
  { code: "CG", name: "Congo (Brazzaville)", flag: "🇨🇬" },
  { code: "CD", name: "RD Congo", flag: "🇨🇩" },
  { code: "CR", name: "Costa Rica", flag: "🇨🇷" },
  { code: "HR", name: "Croatie", flag: "🇭🇷" },
  { code: "CU", name: "Cuba", flag: "🇨🇺" },
  { code: "CY", name: "Chypre", flag: "🇨🇾" },
  { code: "CZ", name: "Tchéquie", flag: "🇨🇿" },
  { code: "DK", name: "Danemark", flag: "🇩🇰" },
  { code: "DJ", name: "Djibouti", flag: "🇩🇯" },
  { code: "DM", name: "Dominique", flag: "🇩🇲" },
  { code: "DO", name: "République dominicaine", flag: "🇩🇴" },
  { code: "EC", name: "Équateur", flag: "🇪🇨" },
  { code: "EG", name: "Égypte", flag: "🇪🇬" },
  { code: "SV", name: "Salvador", flag: "🇸🇻" },
  { code: "GQ", name: "Guinée équatoriale", flag: "🇬🇶" },
  { code: "ER", name: "Érythrée", flag: "🇪🇷" },
  { code: "EE", name: "Estonie", flag: "🇪🇪" },
  { code: "SZ", name: "Eswatini", flag: "🇸🇿" },
  { code: "ET", name: "Éthiopie", flag: "🇪🇹" },
  { code: "FJ", name: "Fidji", flag: "🇫🇯" },
  { code: "FI", name: "Finlande", flag: "🇫🇮" },
  { code: "FR", name: "France", flag: "🇫🇷" },
  { code: "GA", name: "Gabon", flag: "🇬🇦" },
  { code: "GM", name: "Gambie", flag: "🇬🇲" },
  { code: "GE", name: "Géorgie", flag: "🇬🇪" },
  { code: "DE", name: "Allemagne", flag: "🇩🇪" },
  { code: "GH", name: "Ghana", flag: "🇬🇭" },
  { code: "GR", name: "Grèce", flag: "🇬🇷" },
  { code: "GD", name: "Grenade", flag: "🇬🇩" },
  { code: "GT", name: "Guatemala", flag: "🇬🇹" },
  { code: "GN", name: "Guinée", flag: "🇬🇳" },
  { code: "GW", name: "Guinée-Bissau", flag: "🇬🇼" },
  { code: "GY", name: "Guyana", flag: "🇬🇾" },
  { code: "HT", name: "Haïti", flag: "🇭🇹" },
  { code: "HN", name: "Honduras", flag: "🇭🇳" },
  { code: "HU", name: "Hongrie", flag: "🇭🇺" },
  { code: "IS", name: "Islande", flag: "🇮🇸" },
  { code: "IN", name: "Inde", flag: "🇮🇳" },
  { code: "ID", name: "Indonésie", flag: "🇮🇩" },
  { code: "IR", name: "Iran", flag: "🇮🇷" },
  { code: "IQ", name: "Irak", flag: "🇮🇶" },
  { code: "IE", name: "Irlande", flag: "🇮🇪" },
  { code: "IL", name: "Israël", flag: "🇮🇱" },
  { code: "IT", name: "Italie", flag: "🇮🇹" },
  { code: "JM", name: "Jamaïque", flag: "🇯🇲" },
  { code: "JP", name: "Japon", flag: "🇯🇵" },
  { code: "JO", name: "Jordanie", flag: "🇯🇴" },
  { code: "KZ", name: "Kazakhstan", flag: "🇰🇿" },
  { code: "KE", name: "Kenya", flag: "🇰🇪" },
  { code: "KI", name: "Kiribati", flag: "🇰🇮" },
  { code: "KW", name: "Koweït", flag: "🇰🇼" },
  { code: "KG", name: "Kirghizstan", flag: "🇰🇬" },
  { code: "LA", name: "Laos", flag: "🇱🇦" },
  { code: "LV", name: "Lettonie", flag: "🇱🇻" },
  { code: "LB", name: "Liban", flag: "🇱🇧" },
  { code: "LS", name: "Lesotho", flag: "🇱🇸" },
  { code: "LR", name: "Libéria", flag: "🇱🇷" },
  { code: "LY", name: "Libye", flag: "🇱🇾" },
  { code: "LI", name: "Liechtenstein", flag: "🇱🇮" },
  { code: "LT", name: "Lituanie", flag: "🇱🇹" },
  { code: "LU", name: "Luxembourg", flag: "🇱🇺" },
  { code: "MG", name: "Madagascar", flag: "🇲🇬" },
  { code: "MW", name: "Malawi", flag: "🇲🇼" },
  { code: "MY", name: "Malaisie", flag: "🇲🇾" },
  { code: "MV", name: "Maldives", flag: "🇲🇻" },
  { code: "ML", name: "Mali", flag: "🇲🇱" },
  { code: "MT", name: "Malte", flag: "🇲🇹" },
  { code: "MH", name: "Îles Marshall", flag: "🇲🇭" },
  { code: "MR", name: "Mauritanie", flag: "🇲🇷" },
  { code: "MU", name: "Maurice", flag: "🇲🇺" },
  { code: "MX", name: "Mexique", flag: "🇲🇽" },
  { code: "FM", name: "Micronésie", flag: "🇫🇲" },
  { code: "MD", name: "Moldavie", flag: "🇲🇩" },
  { code: "MC", name: "Monaco", flag: "🇲🇨" },
  { code: "MN", name: "Mongolie", flag: "🇲🇳" },
  { code: "ME", name: "Monténégro", flag: "🇲🇪" },
  { code: "MA", name: "Maroc", flag: "🇲🇦" },
  { code: "MZ", name: "Mozambique", flag: "🇲🇿" },
  { code: "MM", name: "Myanmar", flag: "🇲🇲" },
  { code: "NA", name: "Namibie", flag: "🇳🇦" },
  { code: "NR", name: "Nauru", flag: "🇳🇷" },
  { code: "NP", name: "Népal", flag: "🇳🇵" },
  { code: "NL", name: "Pays-Bas", flag: "🇳🇱" },
  { code: "NZ", name: "Nouvelle-Zélande", flag: "🇳🇿" },
  { code: "NI", name: "Nicaragua", flag: "🇳🇮" },
  { code: "NE", name: "Niger", flag: "🇳🇪" },
  { code: "NG", name: "Nigeria", flag: "🇳🇬" },
  { code: "NO", name: "Norvège", flag: "🇳🇴" },
  { code: "OM", name: "Oman", flag: "🇴🇲" },
  { code: "PK", name: "Pakistan", flag: "🇵🇰" },
  { code: "PW", name: "Palaos", flag: "🇵🇼" },
  { code: "PA", name: "Panama", flag: "🇵🇦" },
  { code: "PG", name: "Papouasie-Nouvelle-Guinée", flag: "🇵🇬" },
  { code: "PY", name: "Paraguay", flag: "🇵🇾" },
  { code: "PE", name: "Pérou", flag: "🇵🇪" },
  { code: "PH", name: "Philippines", flag: "🇵🇭" },
  { code: "PL", name: "Pologne", flag: "🇵🇱" },
  { code: "PT", name: "Portugal", flag: "🇵🇹" },
  { code: "QA", name: "Qatar", flag: "🇶🇦" },
  { code: "RO", name: "Roumanie", flag: "🇷🇴" },
  { code: "RU", name: "Russie", flag: "🇷🇺" },
  { code: "RW", name: "Rwanda", flag: "🇷🇼" },
  { code: "KN", name: "Saint-Kitts-et-Nevis", flag: "🇰🇳" },
  { code: "LC", name: "Sainte-Lucie", flag: "🇱🇨" },
  { code: "VC", name: "Saint-Vincent", flag: "🇻🇨" },
  { code: "WS", name: "Samoa", flag: "🇼🇸" },
  { code: "SM", name: "Saint-Marin", flag: "🇸🇲" },
  { code: "ST", name: "Sao Tomé-et-Principe", flag: "🇸🇹" },
  { code: "SA", name: "Arabie saoudite", flag: "🇸🇦" },
  { code: "SN", name: "Sénégal", flag: "🇸🇳" },
  { code: "RS", name: "Serbie", flag: "🇷🇸" },
  { code: "SC", name: "Seychelles", flag: "🇸🇨" },
  { code: "SL", name: "Sierra Leone", flag: "🇸🇱" },
  { code: "SG", name: "Singapour", flag: "🇸🇬" },
  { code: "SK", name: "Slovaquie", flag: "🇸🇰" },
  { code: "SI", name: "Slovénie", flag: "🇸🇮" },
  { code: "SB", name: "Îles Salomon", flag: "🇸🇧" },
  { code: "SO", name: "Somalie", flag: "🇸🇴" },
  { code: "ZA", name: "Afrique du Sud", flag: "🇿🇦" },
  { code: "SS", name: "Soudan du Sud", flag: "🇸🇸" },
  { code: "ES", name: "Espagne", flag: "🇪🇸" },
  { code: "LK", name: "Sri Lanka", flag: "🇱🇰" },
  { code: "SD", name: "Soudan", flag: "🇸🇩" },
  { code: "SR", name: "Suriname", flag: "🇸🇷" },
  { code: "SE", name: "Suède", flag: "🇸🇪" },
  { code: "CH", name: "Suisse", flag: "🇨🇭" },
  { code: "SY", name: "Syrie", flag: "🇸🇾" },
  { code: "TW", name: "Taïwan", flag: "🇹🇼" },
  { code: "TJ", name: "Tadjikistan", flag: "🇹🇯" },
  { code: "TZ", name: "Tanzanie", flag: "🇹🇿" },
  { code: "TH", name: "Thaïlande", flag: "🇹🇭" },
  { code: "TL", name: "Timor oriental", flag: "🇹🇱" },
  { code: "TG", name: "Togo", flag: "🇹🇬" },
  { code: "TO", name: "Tonga", flag: "🇹🇴" },
  { code: "TT", name: "Trinité-et-Tobago", flag: "🇹🇹" },
  { code: "TN", name: "Tunisie", flag: "🇹🇳" },
  { code: "TR", name: "Turquie", flag: "🇹🇷" },
  { code: "TM", name: "Turkménistan", flag: "🇹🇲" },
  { code: "TV", name: "Tuvalu", flag: "🇹🇻" },
  { code: "UG", name: "Ouganda", flag: "🇺🇬" },
  { code: "UA", name: "Ukraine", flag: "🇺🇦" },
  { code: "AE", name: "Émirats arabes unis", flag: "🇦🇪" },
  { code: "GB", name: "Royaume-Uni", flag: "🇬🇧" },
  { code: "US", name: "États-Unis", flag: "🇺🇸" },
  { code: "UY", name: "Uruguay", flag: "🇺🇾" },
  { code: "UZ", name: "Ouzbékistan", flag: "🇺🇿" },
  { code: "VU", name: "Vanuatu", flag: "🇻🇺" },
  { code: "VE", name: "Venezuela", flag: "🇻🇪" },
  { code: "VN", name: "Viêt Nam", flag: "🇻🇳" },
  { code: "YE", name: "Yémen", flag: "🇾🇪" },
  { code: "ZM", name: "Zambie", flag: "🇿🇲" },
  { code: "ZW", name: "Zimbabwe", flag: "🇿🇼" },
];
