/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as publicVideographyRouteImport } from './routes/(public)/videography'
import { Route as publicSuccessRouteImport } from './routes/(public)/success'
import { Route as publicStoreRouteImport } from './routes/(public)/store'
import { Route as publicReleasereleaseIdRouteImport } from './routes/(public)/release$releaseId'
import { Route as publicPressbookRouteImport } from './routes/(public)/pressbook'
import { Route as publicPaymentRouteImport } from './routes/(public)/payment'
import { Route as publicOrdersRouteImport } from './routes/(public)/orders'
import { Route as publicMusicRouteImport } from './routes/(public)/music'
import { Route as publicGalleryRouteImport } from './routes/(public)/gallery'
import { Route as publicContactRouteImport } from './routes/(public)/contact'
import { Route as publicCheckoutRouteImport } from './routes/(public)/checkout'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authEmailVerifiedRouteImport } from './routes/(auth)/email-verified'
import { Route as privateUserIndexRouteImport } from './routes/(private)/user/index'
import { Route as privateAdminIndexRouteImport } from './routes/(private)/admin/index'
import { Route as publicProductProductIdRouteImport } from './routes/(public)/product.$productId'
import { Route as publicPaymentStatusDepositIdRouteImport } from './routes/(public)/payment-status.$depositId'
import { Route as publicAlbumAlbumIdRouteImport } from './routes/(public)/album.$albumId'

const publicIndexRoute = publicIndexRouteImport.update({
  id: '/(public)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicVideographyRoute = publicVideographyRouteImport.update({
  id: '/(public)/videography',
  path: '/videography',
  getParentRoute: () => rootRouteImport,
} as any)
const publicSuccessRoute = publicSuccessRouteImport.update({
  id: '/(public)/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const publicStoreRoute = publicStoreRouteImport.update({
  id: '/(public)/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const publicReleasereleaseIdRoute = publicReleasereleaseIdRouteImport.update({
  id: '/(public)/release$releaseId',
  path: '/release$releaseId',
  getParentRoute: () => rootRouteImport,
} as any)
const publicPressbookRoute = publicPressbookRouteImport.update({
  id: '/(public)/pressbook',
  path: '/pressbook',
  getParentRoute: () => rootRouteImport,
} as any)
const publicPaymentRoute = publicPaymentRouteImport.update({
  id: '/(public)/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const publicOrdersRoute = publicOrdersRouteImport.update({
  id: '/(public)/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const publicMusicRoute = publicMusicRouteImport.update({
  id: '/(public)/music',
  path: '/music',
  getParentRoute: () => rootRouteImport,
} as any)
const publicGalleryRoute = publicGalleryRouteImport.update({
  id: '/(public)/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const publicContactRoute = publicContactRouteImport.update({
  id: '/(public)/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const publicCheckoutRoute = publicCheckoutRouteImport.update({
  id: '/(public)/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authEmailVerifiedRoute = authEmailVerifiedRouteImport.update({
  id: '/(auth)/email-verified',
  path: '/email-verified',
  getParentRoute: () => rootRouteImport,
} as any)
const privateUserIndexRoute = privateUserIndexRouteImport.update({
  id: '/(private)/user/',
  path: '/user/',
  getParentRoute: () => rootRouteImport,
} as any)
const privateAdminIndexRoute = privateAdminIndexRouteImport.update({
  id: '/(private)/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicProductProductIdRoute = publicProductProductIdRouteImport.update({
  id: '/(public)/product/$productId',
  path: '/product/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const publicPaymentStatusDepositIdRoute =
  publicPaymentStatusDepositIdRouteImport.update({
    id: '/(public)/payment-status/$depositId',
    path: '/payment-status/$depositId',
    getParentRoute: () => rootRouteImport,
  } as any)
const publicAlbumAlbumIdRoute = publicAlbumAlbumIdRouteImport.update({
  id: '/(public)/album/$albumId',
  path: '/album/$albumId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/email-verified': typeof authEmailVerifiedRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/checkout': typeof publicCheckoutRoute
  '/contact': typeof publicContactRoute
  '/gallery': typeof publicGalleryRoute
  '/music': typeof publicMusicRoute
  '/orders': typeof publicOrdersRoute
  '/payment': typeof publicPaymentRoute
  '/pressbook': typeof publicPressbookRoute
  '/release$releaseId': typeof publicReleasereleaseIdRoute
  '/store': typeof publicStoreRoute
  '/success': typeof publicSuccessRoute
  '/videography': typeof publicVideographyRoute
  '/': typeof publicIndexRoute
  '/album/$albumId': typeof publicAlbumAlbumIdRoute
  '/payment-status/$depositId': typeof publicPaymentStatusDepositIdRoute
  '/product/$productId': typeof publicProductProductIdRoute
  '/admin/': typeof privateAdminIndexRoute
  '/user/': typeof privateUserIndexRoute
}
export interface FileRoutesByTo {
  '/email-verified': typeof authEmailVerifiedRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/checkout': typeof publicCheckoutRoute
  '/contact': typeof publicContactRoute
  '/gallery': typeof publicGalleryRoute
  '/music': typeof publicMusicRoute
  '/orders': typeof publicOrdersRoute
  '/payment': typeof publicPaymentRoute
  '/pressbook': typeof publicPressbookRoute
  '/release$releaseId': typeof publicReleasereleaseIdRoute
  '/store': typeof publicStoreRoute
  '/success': typeof publicSuccessRoute
  '/videography': typeof publicVideographyRoute
  '/': typeof publicIndexRoute
  '/album/$albumId': typeof publicAlbumAlbumIdRoute
  '/payment-status/$depositId': typeof publicPaymentStatusDepositIdRoute
  '/product/$productId': typeof publicProductProductIdRoute
  '/admin': typeof privateAdminIndexRoute
  '/user': typeof privateUserIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)/email-verified': typeof authEmailVerifiedRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/(public)/checkout': typeof publicCheckoutRoute
  '/(public)/contact': typeof publicContactRoute
  '/(public)/gallery': typeof publicGalleryRoute
  '/(public)/music': typeof publicMusicRoute
  '/(public)/orders': typeof publicOrdersRoute
  '/(public)/payment': typeof publicPaymentRoute
  '/(public)/pressbook': typeof publicPressbookRoute
  '/(public)/release$releaseId': typeof publicReleasereleaseIdRoute
  '/(public)/store': typeof publicStoreRoute
  '/(public)/success': typeof publicSuccessRoute
  '/(public)/videography': typeof publicVideographyRoute
  '/(public)/': typeof publicIndexRoute
  '/(public)/album/$albumId': typeof publicAlbumAlbumIdRoute
  '/(public)/payment-status/$depositId': typeof publicPaymentStatusDepositIdRoute
  '/(public)/product/$productId': typeof publicProductProductIdRoute
  '/(private)/admin/': typeof privateAdminIndexRoute
  '/(private)/user/': typeof privateUserIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/email-verified'
    | '/login'
    | '/register'
    | '/checkout'
    | '/contact'
    | '/gallery'
    | '/music'
    | '/orders'
    | '/payment'
    | '/pressbook'
    | '/release$releaseId'
    | '/store'
    | '/success'
    | '/videography'
    | '/'
    | '/album/$albumId'
    | '/payment-status/$depositId'
    | '/product/$productId'
    | '/admin/'
    | '/user/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/email-verified'
    | '/login'
    | '/register'
    | '/checkout'
    | '/contact'
    | '/gallery'
    | '/music'
    | '/orders'
    | '/payment'
    | '/pressbook'
    | '/release$releaseId'
    | '/store'
    | '/success'
    | '/videography'
    | '/'
    | '/album/$albumId'
    | '/payment-status/$depositId'
    | '/product/$productId'
    | '/admin'
    | '/user'
  id:
    | '__root__'
    | '/(auth)/email-verified'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/(public)/checkout'
    | '/(public)/contact'
    | '/(public)/gallery'
    | '/(public)/music'
    | '/(public)/orders'
    | '/(public)/payment'
    | '/(public)/pressbook'
    | '/(public)/release$releaseId'
    | '/(public)/store'
    | '/(public)/success'
    | '/(public)/videography'
    | '/(public)/'
    | '/(public)/album/$albumId'
    | '/(public)/payment-status/$depositId'
    | '/(public)/product/$productId'
    | '/(private)/admin/'
    | '/(private)/user/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authEmailVerifiedRoute: typeof authEmailVerifiedRoute
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
  publicCheckoutRoute: typeof publicCheckoutRoute
  publicContactRoute: typeof publicContactRoute
  publicGalleryRoute: typeof publicGalleryRoute
  publicMusicRoute: typeof publicMusicRoute
  publicOrdersRoute: typeof publicOrdersRoute
  publicPaymentRoute: typeof publicPaymentRoute
  publicPressbookRoute: typeof publicPressbookRoute
  publicReleasereleaseIdRoute: typeof publicReleasereleaseIdRoute
  publicStoreRoute: typeof publicStoreRoute
  publicSuccessRoute: typeof publicSuccessRoute
  publicVideographyRoute: typeof publicVideographyRoute
  publicIndexRoute: typeof publicIndexRoute
  publicAlbumAlbumIdRoute: typeof publicAlbumAlbumIdRoute
  publicPaymentStatusDepositIdRoute: typeof publicPaymentStatusDepositIdRoute
  publicProductProductIdRoute: typeof publicProductProductIdRoute
  privateAdminIndexRoute: typeof privateAdminIndexRoute
  privateUserIndexRoute: typeof privateUserIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/videography': {
      id: '/(public)/videography'
      path: '/videography'
      fullPath: '/videography'
      preLoaderRoute: typeof publicVideographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/success': {
      id: '/(public)/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof publicSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/store': {
      id: '/(public)/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof publicStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/release$releaseId': {
      id: '/(public)/release$releaseId'
      path: '/release$releaseId'
      fullPath: '/release$releaseId'
      preLoaderRoute: typeof publicReleasereleaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/pressbook': {
      id: '/(public)/pressbook'
      path: '/pressbook'
      fullPath: '/pressbook'
      preLoaderRoute: typeof publicPressbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/payment': {
      id: '/(public)/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof publicPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/orders': {
      id: '/(public)/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof publicOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/music': {
      id: '/(public)/music'
      path: '/music'
      fullPath: '/music'
      preLoaderRoute: typeof publicMusicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/gallery': {
      id: '/(public)/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof publicGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/contact': {
      id: '/(public)/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof publicContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/checkout': {
      id: '/(public)/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof publicCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/email-verified': {
      id: '/(auth)/email-verified'
      path: '/email-verified'
      fullPath: '/email-verified'
      preLoaderRoute: typeof authEmailVerifiedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/user/': {
      id: '/(private)/user/'
      path: '/user'
      fullPath: '/user/'
      preLoaderRoute: typeof privateUserIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/admin/': {
      id: '/(private)/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof privateAdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/product/$productId': {
      id: '/(public)/product/$productId'
      path: '/product/$productId'
      fullPath: '/product/$productId'
      preLoaderRoute: typeof publicProductProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/payment-status/$depositId': {
      id: '/(public)/payment-status/$depositId'
      path: '/payment-status/$depositId'
      fullPath: '/payment-status/$depositId'
      preLoaderRoute: typeof publicPaymentStatusDepositIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/album/$albumId': {
      id: '/(public)/album/$albumId'
      path: '/album/$albumId'
      fullPath: '/album/$albumId'
      preLoaderRoute: typeof publicAlbumAlbumIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  authEmailVerifiedRoute: authEmailVerifiedRoute,
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
  publicCheckoutRoute: publicCheckoutRoute,
  publicContactRoute: publicContactRoute,
  publicGalleryRoute: publicGalleryRoute,
  publicMusicRoute: publicMusicRoute,
  publicOrdersRoute: publicOrdersRoute,
  publicPaymentRoute: publicPaymentRoute,
  publicPressbookRoute: publicPressbookRoute,
  publicReleasereleaseIdRoute: publicReleasereleaseIdRoute,
  publicStoreRoute: publicStoreRoute,
  publicSuccessRoute: publicSuccessRoute,
  publicVideographyRoute: publicVideographyRoute,
  publicIndexRoute: publicIndexRoute,
  publicAlbumAlbumIdRoute: publicAlbumAlbumIdRoute,
  publicPaymentStatusDepositIdRoute: publicPaymentStatusDepositIdRoute,
  publicProductProductIdRoute: publicProductProductIdRoute,
  privateAdminIndexRoute: privateAdminIndexRoute,
  privateUserIndexRoute: privateUserIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
